- name: Provision Fedora CSB Playbook
  hosts: desktop
  gather_facts: true
  vars_files:
    - vars/packages-dnf.yaml
    - vars/remote-non-repo-rpms.yaml
    - vars/printers.yaml
  tasks:

  ############################# dnf Packages ##############################
  - name: (DNF) Ensure Distro repo packages are up to date
    ansible.builtin.dnf:
      name: "*"
      state: latest
    tags:
      - pkg_update
  
  - name: (DNF) Ensure RPM Fusion Fedora Repos are Enabled
    ansible.builtin.dnf:
      state: present
      name:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      disable_gpg_check: yes

  - name: (DNF) Ensure dnf repo packages are present
    ansible.builtin.dnf:
      update_cache: yes
      name: "{{ base_packages + kde_packages + fusion_free_packages + fusion_nonfree_packages }}"
      allowerasing: yes
      state: present

  - name: (DNF) Ensure Remote Non-Repo Packages are up to Date
    ansible.builtin.dnf:
      disable_gpg_check: yes
      name: "{{ remote_non_repo_rpms }}"
      state: present

  ############################# Local rpm packages ##############################
  - name: "(Local rpm) Finding {{ for_user }}'s Local rpms"
    ansible.builtin.find:
      paths: "/home/{{ for_user }}/automated-install/rpm"
      patterns: "*.rpm"
    register: local_rpm_results
  - name: "(Local rpm) Prepare {{ for_user }}'s Local rpm List"
    ansible.builtin.set_fact:
      rpm_paths: "{{ local_rpm_results.files | map(attribute='path') | list}}"
  - name: "(Local rpm) Ensure {{ for_user }}'s Local rpm packages are Installed"
    ansible.builtin.dnf:
      name: "{{ rpm_paths }}"
      state: present
      disable_gpg_check: yes
  
  ############# Libvirt Config -- To move to a role some day #####################
  - name: (libvirt) Ensure iptables is the backend firewall for libvirt Networking
    lineinfile:
      path: /etc/libvirt/network.conf
      line: 'firewall_backend  = "iptables"'
      state: present
  - name: (libvirt) Ensure nftables is NOT the backend firewall for libvirt Networking
    lineinfile:
      path: /etc/libvirt/network.conf
      line: 'firewall_backend  = "nftables"'
      state: absent
  - name: "(libvirt) Ensure user: {{ for_user }} is in the libvirt group"
    user:
      name: "{{ for_user }}"
      groups: libvirt
      append: yes
  - name: (libvirt) Ensure libvirtd is enable and started
    systemd:
      name: libvirtd
      enabled: yes
      state: started
  ################################################################################


############################## Printers ########################################
  - name: (Printers) Ensure avahi-daemon (for automatic printer detection) is enable and started
    systemd:
      name: avahi-daemon
      enabled: yes
      state: started

  - name: (Printers) Ensure home printers are present
    ansible.builtin.command: >
      lpadmin
      -p {{ item.name }}
      -E
      -v {{ item.uri }}
      -m {{ item.driver | default('everywhere') }}
      -D "{{ item.description }}"
      -L "{{ item.location }}"
    args:
      creates: "/etc/cups/ppd/{{ item.name }}.ppd"
    loop: "{{ printers }}"

############################## Other Playbooks ########################################
- import_playbook: provision-user-settings.yaml
  vars:
    provisioned_user: "{{ for_user }}"

- import_playbook: provision-snaps.yaml

- import_playbook: provision-roles.yaml
  vars:
    provisioned_user: "{{ for_user }}"
