- name: Provision Fedora CSB Playbook
  hosts: desktop
  gather_facts: true
  vars_files:
    - vars/packages-dnf.yaml
    - vars/remote-non-repo-rpms.yaml
  tasks:

  ############################# dnf Packages ##############################
  - name: Ensure Distro dnf repo packages are up to date
    ansible.builtin.dnf:
      name: "*"
      state: latest
    tags:
      - pkg_update
  
  - name: Ensure RPM Fusion Fedora Repos are Enabled
    ansible.builtin.dnf:
      state: present
      name:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      disable_gpg_check: yes

  - name: Ensure dnf repo packages are present
    ansible.builtin.dnf:
      update_cache: yes
      name: "{{ base_packages + kde_packages + fusion_free_packages + fusion_nonfree_packages }}"
      allowerasing: yes
      state: present

  - name: Ensure Remote Non-Repo Packages are up to Date
    ansible.builtin.dnf:
      disable_gpg_check: yes
      name: "{{ remote_non_repo_rpms }}"
      state: present

  ############################# Local rpm packages ##############################
  - name: "(Local rpm) Finding {{ for_user }}'s Local rpms"
    ansible.builtin.find:
      paths: "/home/{{ for_user }}/automated-install/rpm"
      patterns: "*.rpm"
    register: local_rpm_results
  - name: "(Local rpm) Prepare {{ for_user }}'s Local rpm List"
    ansible.builtin.set_fact:
      rpm_paths: "{{ local_rpm_results.files | map(attribute='path') | list}}"
  - name: "(Local rpm) Ensure {{ for_user }}'s Local rpm packages are Installed"
    ansible.builtin.dnf:
      name: "{{ rpm_paths }}"
      state: present
      disable_gpg_check: yes
  
  ############################## User Account ########################################

  - name: "Ensure user: {{ for_user }} is in the libvirt supplemental group"
    user:
      name: "{{ for_user }}"
      groups: libvirt
      append: yes
 
  ############################## Systemd ########################################

  - name: Ensure avahi-daemon is enable and started (for automatic printer detection)
    ansible.builtin.systemd:
      name: avahi-daemon
      enabled: yes
      state: started

  - name: Ensure libvirtd is enable and started (For VMs)
    systemd:
      name: libvirtd
      enabled: yes
      state: started

############################## SDDM ####################################################
  - name: Gather Package Facts
    ansible.builtin.package_facts:
      manager: auto
  - name: Configure SDDM Settings
    block:
      - name: Ensure sddm is enabled and started (for preferred login manager) 
        ansible.builtin.systemd:
          name: sddm
          enabled: yes
          force: yes
          state: started

      - name: Get the UID of the target user
        ansible.builtin.getent:
          database: passwd
          key: "{{ for_user }}"

      - name: Set target_uid variable
        ansible.builtin.set_fact:
          target_uid: "{{ ansible_facts.getent_passwd[for_user][1] }}"

      - name: Ensure SDDM config directory exists
        ansible.builtin.file:
          path: /etc/sddm.conf.d
          state: directory
          mode: '0755'

      - name: "Configure [Users] section in sddm.conf to show {{ for_user }}"
        community.general.ini_file:
          path: /etc/sddm.conf
          section: Users
          option: "{{ item.key }}"
          value: "{{ item.value }}"
          mode: '0644'
        loop:
          # Enable the "Remember Last User" feature
          - { key: 'RememberLastUser', value: "true" }
          # Clear any manual blacklist that might be hiding the user
          - { key: 'HideUsers', value: "" }
          # Ensure the minimum UID is the user's UID
          - { key: 'MinimumUid', value: "{{ target_uid }}" }
          # Ensure the maximum UID is the user's UID
          - { key: 'MaximumUid', value: "{{ target_uid }}" }

      - name: Ensure SDDM state directory exists
        ansible.builtin.file:
          path: /var/lib/sddm
          state: directory
          owner: sddm
          group: sddm
          mode: '0750'

      - name: "Set {{ for_user }} as the Last Logged In user, so they default"
        community.general.ini_file:
          path: /var/lib/sddm/state.conf
          section: Last
          option: User
          value: "{{ for_user }}"
          mode: '0644'
          no_extra_spaces: true

      - name: Set session default to Plasma
        community.general.ini_file:
          path: /var/lib/sddm/state.conf
          section: Last
          option: Session
          value: "/usr/share/wayland-sessions/plasma.desktop"

    when: ansible_facts.packages['sddm'] is defined

############################## Other Playbooks ########################################
- import_playbook: provision-user-settings.yaml
  vars:
    provisioned_user: "{{ for_user }}"

- import_playbook: provision-snaps.yaml

- import_playbook: provision-roles.yaml
  vars:
    provisioned_user: "{{ for_user }}"
